development:
  adapter: postgresql
  encoding: unicode
  database: art_eventz_development
test:
  adapter: postgresql
  encoding: unicode
  database: art_eventz_test

production:
  adapter: postgresql
  encoding: unicode
  database: art_eventz_production

